spring:
  application:
    name: event-coupon-issuance-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/reservation
  jpa:
    hibernate:
      ddl-auto: create